# Generated by Django 3.2.7 on 2022-05-27 21:01

import algorithm.models
from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_remove_algorithm_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('kNN', 'kNN')], default=None, enum_class=algorithm.models.AlgorithmEnumType, max_length=3, null=True, unique=True),
        ),
    ]
