# Generated by Django 3.2.7 on 2021-10-15 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, verbose_name='Название базы прецедентов')),
                ('public', models.BooleanField(default=True, verbose_name='Публичность базы')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='result.result')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, verbose_name='Название параметра')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'integer'), (2, 'float'), (3, 'string')])),
                ('description', models.CharField(max_length=150, verbose_name='Описание параметра')),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='data_set.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, verbose_name='Название решения')),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='data_set.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=150, verbose_name='Значение результата')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_values', to='data_set.solution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=150, verbose_name='Значение параметра')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='data_set.parameter')),
                ('solution_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='data_set.solutionvalue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
